# Generated by Django 3.1.2 on 2020-11-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201101_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='source_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
